-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE public."FactProduct"
(
    ProductID SERIAL integer NOT NULL,
    ProductName varchar(100) NOT NULL,
    OriginalPrice bigint,
    DiscountedPrice bigint NOT NULL,  
    Discount integer,
    RatingScore float,
    ReviewCount integer,
    SoldItem integer,
    CategoryID integer NOT NULL,
    SellerID integer NOT NULL,
    BrandID integer NOT NULL,
    PRIMARY KEY (ProductID)
);
CREATE TABLE public."DimCategory"
(
    CategoryID SERIAL integer NOT NULL,
    Categoryname varchar(30) NOT NULL,
    PRIMARY KEY (categoryID)
);
CREATE TABLE public."DimSeller"
(
    SellerID SERIAL integer NOT NULL,
    Sellername varchar(30) NOT NULL,
    YearOfEx integer NOT NULL,
    SellerLocation varchar(30), 
    PRIMARY KEY (SellerID)
);
CREATE TABLE public."DimBrand"
(
    BrandID SERIAL integer NOT NULL,
    BrandName varchar(30) NOT NULL,
    YearOfEx integer NOT NULL,
    BrandCountry varchar(30),
    PRIMARY KEY (BrandID)
);
ALTER TABLE public."FactProduct"
    ADD FOREIGN KEY (CategoryID)
    REFERENCES public."DimCategory" (CategoryID)
    NOT VALID;


ALTER TABLE public."FactProduct"
    ADD FOREIGN KEY (SellerID)
    REFERENCES public."DimSeller" (SellerID)
    NOT VALID;

ALTER TABLE public."FactProduct"
    ADD FOREIGN KEY (BrandID)
    REFERENCES public."DimBrand" (BrandID)
    NOT VALID;

END;